name: release catcher.mx.ax
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          tags: ghcr.io/jawr/catcher:latest
          push: true
